### ISSUE TITLE
Issue in Creating Structure Images with RDKit and Python3

### ISSUE THREAD

**Issue by mwang87** [mwang87/ChemicalStructureWebService#3]
To reproduce the problem, in the rdkit_integration branch, we can build the docker container:

make build

Start up the webserver in dev mode:

make dev-server

Try hitting the webserver url:

http://localhost:5066/structureimg?smiles=CN1C=NC2=C1C(=O)N(C(=O)N2C)C&width=500&height=400

It produces this error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/views.py", line 120, in structureimg
    structure_images = MolToImage(m, subImgSize=(width, height), legends=None)
  File "/usr/lib/python3/dist-packages/rdkit/Chem/Draw/__init__.py", line 102, in MolToImage
    img, canvas = _createCanvas(size)
  File "/usr/lib/python3/dist-packages/rdkit/Chem/Draw/__init__.py", line 57, in _createCanvas
    canvas = Canvas(img)
  File "/usr/lib/python3/dist-packages/rdkit/Chem/Draw/cairoCanvas.py", line 170, in __init__
    image.size[1], stride)
NotImplementedError: Surface.create_for_data: Not Implemented yet.

**Comment by jvansan** [comment]
I believe this is an issue caused by the version of python running in Docker image. 

In my experience, the miniconda docker image works great for running RDKit in docker. It does take longer to build, but I've never had RDKit work without conda myself. I'll create a PR with the updates needed.
